---
- name: tao loopback
  hosts: all
  gather_facts: no

  tasks:
    - name: Set loopback IPv4 address
      ios_l3_interface:
        name: loopback {{ item.number }}
	ipv4: 10.0.{{ item.number }}.1/24
      with_items:
        - { number: 1}
        - { number: 2}
        - { number: 3}

    - name: Show loopback
      ios_command:
        commands:
          - show interface loopback
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
